---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mahesh
spec:
  replicas: 4
  selector:
    matchLabels:
      name: deployment
  template:
    metadata:
      name: webapp
      labels:
        name: deployment
    spec:
      containers:
        - name: deploy
          image: maheshgowdamg25/kube:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: maheshservice
spec:
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30070
  selector:
    name: deployment
  type: NodePort
